In [13]:
# M.D.P. Wijesuriya
# 18-7-2025

# Tensor Exercises

In [14]:
import torch

# 1. Tensor Creation

In [15]:
# Create a tensor of shape (5, 3) filled with random values.
tensor = torch.rand(5, 3)

print("Tensor of shape (5, 3):")
print(tensor)

Tensor of shape (5, 3):
tensor([[0.2939, 0.2915, 0.9782],
        [0.6973, 0.0778, 0.7121],
        [0.9224, 0.6548, 0.0025],
        [0.4825, 0.1414, 0.2840],
        [0.1120, 0.1887, 0.0331]])


In [16]:
# Create a tensor of shape (2, 4) filled with ones.
tensor = torch.ones(2, 4)

print("Tensor of shape (2, 4) filled with ones:")
print(tensor)

Tensor of shape (2, 4) filled with ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
# Create a tensor from a list [5, 10, 15, 20].
tensor = torch.tensor([5, 10, 15, 20])

print("Tensor from list:")
print(tensor)

Tensor from list:
tensor([ 5, 10, 15, 20])


In [18]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.
image_tensor = torch.rand(3, 6, 8)

print("Image Tensor shape:", image_tensor.shape)

Image Tensor shape: torch.Size([3, 6, 8])


# 2. Tensor Indexing and Slicing

In [19]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
# Create a 1D tensor with values from 10 to 21 (22 is exclusive)
values = torch.arange(10, 22)

# Reshape it to (3, 4)
tensor = values.reshape(3, 4)

print("Tensor of shape (3, 4) with values from 10 to 21:")
print(tensor)

Tensor of shape (3, 4) with values from 10 to 21:
tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [20]:
image_tensor

tensor([[[0.9062, 0.4181, 0.9499, 0.6389, 0.7690, 0.4606, 0.5720, 0.2200],
         [0.1663, 0.0093, 0.2394, 0.7815, 0.7676, 0.1431, 0.5942, 0.9651],
         [0.1312, 0.6596, 0.3926, 0.7909, 0.6088, 0.9058, 0.8358, 0.5060],
         [0.2992, 0.9759, 0.9804, 0.7028, 0.3534, 0.3440, 0.4070, 0.2401],
         [0.5375, 0.0645, 0.4732, 0.6911, 0.6302, 0.8493, 0.6332, 0.6298],
         [0.3412, 0.5490, 0.9581, 0.0172, 0.1012, 0.1853, 0.2146, 0.0999]],

        [[0.5264, 0.5817, 0.9590, 0.5436, 0.0826, 0.9782, 0.1353, 0.3647],
         [0.5615, 0.4168, 0.4895, 0.4496, 0.1106, 0.6138, 0.3980, 0.9659],
         [0.7415, 0.0705, 0.6208, 0.0324, 0.1053, 0.7073, 0.4817, 0.0558],
         [0.7050, 0.1671, 0.4459, 0.6229, 0.8388, 0.3346, 0.3330, 0.5860],
         [0.0912, 0.0979, 0.4656, 0.5937, 0.7320, 0.2561, 0.9247, 0.3012],
         [0.1657, 0.7032, 0.0742, 0.9990, 0.7778, 0.4600, 0.7679, 0.9287]],

        [[0.0281, 0.8931, 0.5169, 0.4787, 0.5419, 0.0813, 0.5849, 0.5080],
         [0.1271, 0.7

In [21]:
# Access the element at the second row, third column.
element = image_tensor[0, 1, 2]
print("Element at channel 0, row 1, column 2:", element)

Element at channel 0, row 1, column 2: tensor(0.2394)


In [22]:
# Print the second row.
second_row = image_tensor[:, 1, :]  # This means All channels, row 1, all columns
print("Second row (across all channels):")
print(second_row)

Second row (across all channels):
tensor([[0.1663, 0.0093, 0.2394, 0.7815, 0.7676, 0.1431, 0.5942, 0.9651],
        [0.5615, 0.4168, 0.4895, 0.4496, 0.1106, 0.6138, 0.3980, 0.9659],
        [0.1271, 0.7593, 0.6312, 0.3739, 0.1961, 0.4741, 0.2309, 0.5768]])


In [23]:
# Print the first two columns.
first_two_columns = image_tensor[:, :, :2]  # This means All channels, all rows, first 2 columns
print("First two columns (across all rows and channels):")
print(first_two_columns)

First two columns (across all rows and channels):
tensor([[[0.9062, 0.4181],
         [0.1663, 0.0093],
         [0.1312, 0.6596],
         [0.2992, 0.9759],
         [0.5375, 0.0645],
         [0.3412, 0.5490]],

        [[0.5264, 0.5817],
         [0.5615, 0.4168],
         [0.7415, 0.0705],
         [0.7050, 0.1671],
         [0.0912, 0.0979],
         [0.1657, 0.7032]],

        [[0.0281, 0.8931],
         [0.1271, 0.7593],
         [0.1229, 0.1185],
         [0.2202, 0.4401],
         [0.8611, 0.4975],
         [0.5595, 0.7001]]])


# 3. Tensor Arithmetic Operations

In [24]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.
tensor_a = torch.rand(3, 3)
tensor_b = torch.rand(3, 3)

print("Tensor A:")
print(tensor_a)

print("\n")

print("\nTensor B:")
print(tensor_b)

Tensor A:
tensor([[0.7948, 0.6802, 0.8606],
        [0.9089, 0.8481, 0.4059],
        [0.3656, 0.1895, 0.7250]])



Tensor B:
tensor([[0.0403, 0.7547, 0.4321],
        [0.9625, 0.0337, 0.5705],
        [0.6830, 0.5269, 0.2526]])


In [25]:
# Perform element-wise addition.

In [26]:
# Perform element-wise multiplication.

In [27]:
# Subtract tensor_b from tensor_a.

# 4. Tensor Aggregation Operations

In [28]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.

In [29]:
# Compute the sum of all elements.

In [30]:
# Compute the mean of all elements.

In [31]:
# Find the maximum and minimum values.

In [32]:
# Compute the sum along the rows.

In [33]:
# Compute the mean along the columns.

# 5. Tensor Reshaping Operations

In [34]:
# Create a tensor tensor of shape (2, 3, 4) with random values.

In [35]:
# Reshape the tensor to (4, 6).

In [36]:
# Transpose the tensor (swap the first and second dimensions).

In [37]:
# Flatten the tensor to a 1D tensor.

# 6. Tensor Broadcasting

In [38]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.

In [39]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].

In [40]:
# Perform broadcasting addition.

In [41]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].

In [42]:
# Perform broadcasting multiplication.

# 7. Tensor Device Management

In [43]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).

In [44]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

# 8. Tensor Cloning and Detaching

In [45]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.

In [46]:
# Clone the tensor and print the cloned tensor.

In [47]:
# Detach the tensor from the computation graph and print the detached tensor.

# 9. High Dimensional Tensors

In [48]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.

In [49]:
# Print the shape of the tensor.

In [50]:
# Access the element at position (1, 2, 3, 4).

In [51]:
# Slice and print the first two elements along the first dimension.

In [52]:
# Sum all elements in the tensor.

In [53]:
# Compute the mean along the third dimension.

# 10. Combining Tensor Operations

In [54]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.

In [55]:
# Add the two tensors.

In [56]:
# Multiply the resulting tensor by 2.

In [57]:
# Reshape the tensor to (4, 6).

In [58]:
# Compute the sum along the columns.

-------------------------------------------- END ----------------------------------------------