In [ ]:
# M.D.P. Wijesuriya
# 18-7-2025

# Tensor Exercises

In [1]:
import torch

# 1. Tensor Creation

In [2]:
# Create a tensor of shape (5, 3) filled with random values.
tensor = torch.rand(5, 3)

print("Tensor of shape (5, 3):")
print(tensor)

Tensor of shape (5, 3):
tensor([[0.9603, 0.2590, 0.5690],
        [0.2027, 0.2467, 0.7345],
        [0.8692, 0.9702, 0.3069],
        [0.0626, 0.1003, 0.4503],
        [0.4375, 0.8613, 0.9891]])


In [3]:
# Create a tensor of shape (2, 4) filled with ones.
tensor = torch.ones(2, 4)

print("Tensor of shape (2, 4) filled with ones:")
print(tensor)

Tensor of shape (2, 4) filled with ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [4]:
# Create a tensor from a list [5, 10, 15, 20].
tensor = torch.tensor([5, 10, 15, 20])

print("Tensor from list:")
print(tensor)

Tensor from list:
tensor([ 5, 10, 15, 20])


In [ ]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.

# 2. Tensor Indexing and Slicing

In [5]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
image_tensor = torch.rand(3, 6, 8)

print("Image Tensor shape:", image_tensor.shape)

Image Tensor shape: torch.Size([3, 6, 8])


In [7]:
image_tensor

tensor([[[0.6584, 0.4372, 0.1179, 0.2812, 0.7577, 0.1479, 0.9685, 0.1862],
         [0.1112, 0.9103, 0.1488, 0.8587, 0.5635, 0.7134, 0.6678, 0.4943],
         [0.1454, 0.3486, 0.9496, 0.6102, 0.9411, 0.3020, 0.9652, 0.6953],
         [0.9021, 0.1844, 0.1515, 0.3367, 0.4753, 0.7513, 0.4108, 0.1865],
         [0.1933, 0.8062, 0.5505, 0.2925, 0.1750, 0.3843, 0.7750, 0.6723],
         [0.2137, 0.8967, 0.4837, 0.4169, 0.0484, 0.5299, 0.0336, 0.0961]],

        [[0.8995, 0.9932, 0.2382, 0.3348, 0.9739, 0.2257, 0.9662, 0.5810],
         [0.8714, 0.1618, 0.0720, 0.8905, 0.9330, 0.4844, 0.1960, 0.3217],
         [0.6972, 0.0502, 0.3768, 0.3260, 0.0235, 0.1451, 0.2712, 0.7980],
         [0.1568, 0.9615, 0.9285, 0.8504, 0.3915, 0.2572, 0.3020, 0.9764],
         [0.0242, 0.5624, 0.2012, 0.9530, 0.4735, 0.4961, 0.9544, 0.7652],
         [0.3734, 0.6137, 0.5953, 0.4747, 0.1151, 0.5677, 0.7622, 0.5595]],

        [[0.3945, 0.5089, 0.6328, 0.3877, 0.1222, 0.6224, 0.6580, 0.1520],
         [0.5519, 0.1

In [6]:
# Access the element at the second row, third column.
element = image_tensor[0, 1, 2]
print("Element at channel 0, row 1, column 2:", element)

Element at channel 0, row 1, column 2: tensor(0.1488)


In [9]:
# Print the second row.
second_row = image_tensor[:, 1, :]  # This means All channels, row 1, all columns
print("Second row (across all channels):")
print(second_row)

Second row (across all channels):
tensor([[0.0305, 0.3125, 0.0179, 0.3926, 0.5481, 0.0031, 0.7893, 0.1611],
        [0.2478, 0.9395, 0.5630, 0.5244, 0.6300, 0.1125, 0.5976, 0.2234],
        [0.0308, 0.6093, 0.0334, 0.2829, 0.3106, 0.6402, 0.6738, 0.2856]])


In [10]:
# Print the first two columns.
first_two_columns = image_tensor[:, :, :2]  # This means All channels, all rows, first 2 columns
print("First two columns (across all rows and channels):")
print(first_two_columns)

First two columns (across all rows and channels):
tensor([[[0.7010, 0.4054],
         [0.0305, 0.3125],
         [0.6351, 0.1624],
         [0.1415, 0.7161],
         [0.7157, 0.2106],
         [0.4675, 0.1767]],

        [[0.4654, 0.0061],
         [0.2478, 0.9395],
         [0.8106, 0.4176],
         [0.3846, 0.3339],
         [0.5006, 0.8077],
         [0.2265, 0.4901]],

        [[0.4281, 0.2998],
         [0.0308, 0.6093],
         [0.6489, 0.2156],
         [0.6135, 0.3191],
         [0.2245, 0.5047],
         [0.0087, 0.0296]]])


# 3. Tensor Arithmetic Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.
tensor_a = torch.rand(3, 3)
tensor_b = torch.rand(3, 3)

print("Tensor A:")
print(tensor_a)

print("\n")

print("\nTensor B:")
print(tensor_b)

In [ ]:
# Perform element-wise addition.

In [ ]:
# Perform element-wise multiplication.

In [ ]:
# Subtract tensor_b from tensor_a.

# 4. Tensor Aggregation Operations

In [ ]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.

In [ ]:
# Compute the sum of all elements.

In [ ]:
# Compute the mean of all elements.

In [ ]:
# Find the maximum and minimum values.

In [ ]:
# Compute the sum along the rows.

In [ ]:
# Compute the mean along the columns.

# 5. Tensor Reshaping Operations

In [ ]:
# Create a tensor tensor of shape (2, 3, 4) with random values.

In [ ]:
# Reshape the tensor to (4, 6).

In [ ]:
# Transpose the tensor (swap the first and second dimensions).

In [ ]:
# Flatten the tensor to a 1D tensor.

# 6. Tensor Broadcasting

In [ ]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.

In [ ]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].

In [ ]:
# Perform broadcasting addition.

In [ ]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].

In [ ]:
# Perform broadcasting multiplication.

# 7. Tensor Device Management

In [ ]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).

In [ ]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

# 8. Tensor Cloning and Detaching

In [ ]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.

In [ ]:
# Clone the tensor and print the cloned tensor.

In [ ]:
# Detach the tensor from the computation graph and print the detached tensor.

# 9. High Dimensional Tensors

In [ ]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.

In [ ]:
# Print the shape of the tensor.

In [ ]:
# Access the element at position (1, 2, 3, 4).

In [ ]:
# Slice and print the first two elements along the first dimension.

In [ ]:
# Sum all elements in the tensor.

In [ ]:
# Compute the mean along the third dimension.

# 10. Combining Tensor Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.

In [ ]:
# Add the two tensors.

In [ ]:
# Multiply the resulting tensor by 2.

In [ ]:
# Reshape the tensor to (4, 6).

In [ ]:
# Compute the sum along the columns.

-------------------------------------------- END ----------------------------------------------