In [ ]:
# Sumani
# 20-7-2024

# 1. Introduction to Tensors

A tensor represents a (possibly multidimensional) array of numerical values. 
1. In the zero dimensional case, a tensor is called a scalar. 
2. In the one dimensional case, i.e., when only one axis is needed for the data, a tensor is called a vector.
3. With two axes, a tensor is called a matrix.
4. With 𝑘 > 2 axes, we drop the specialized names and just refer to the object as a 𝑘 th order tensor.

Complex computations often involve combining multiple tensor operations. For example, adding tensors, performing element-wise operations, reshaping, and aggregating results in a single sequence. Understanding how different operations interact and combining them effectively is crucial for efficient tensor manipulations.

In [1]:
# To start, we import the PyTorch library. Note that the package name is torch.
import torch
torch.__version__

'2.7.1+cpu'

# 1.1 Scalars
Scalars: Scalars are single numerical values. They have magnitude but no direction. Examples include temperature, mass, and time.


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

## 1.2 Vectors
Vectors: Vectors are quantities with both magnitude and direction. They are represented by arrows. Examples include velocity, force, and displacement.

In [4]:
vector = torch.tensor([7, 3, 7])
vector

tensor([7, 3, 7])

In [5]:
vector.shape

torch.Size([3])

## 1.3 Matrix
Matrices: Matrices are 2-D arrays of numbers. They are used to represent data or transformations. A matrix has rows and columns. For example:

[[7, 8], [9, 6]]

In [6]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.shape

torch.Size([2, 2])

## 1.4 Tensors

Tensors generalize scalars, vectors, and matrices to higher dimensions. They are used in deep learning and represent multi-dimensional data.

In [8]:
# Tensor
TENSOR = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [9]:
TENSOR.ndim

4

# 2. Creating Tensors

 Tensors can be created from lists, numpy arrays, or by using various PyTorch functions like `torch.tensor()`, `torch.zeros()`, `torch.ones()`, `torch.rand()`, etc. These functions allow creating tensors of specific shapes filled with zeros, ones, or random values.

## 2.1 Random, ones and zeros

In [10]:
# Create a tensor filled with zeros
zeros_tensor = torch.zeros((3, 4))
print("Zeros Tensor:\n", zeros_tensor, "\n")

Zeros Tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



In [11]:
# Create a tensor filled with ones
ones_tensor = torch.ones((2, 3))
print("Ones Tensor:\n", ones_tensor, "\n")

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [12]:
# Create a tensor with random values
random_tensor = torch.rand((3, 3))
print("Random Tensor:\n", random_tensor, "\n")

Random Tensor:
 tensor([[0.2418, 0.5873, 0.1999],
        [0.4893, 0.6961, 0.3791],
        [0.4725, 0.4879, 0.3360]]) 



In [13]:
# Create a tensor from a list
list_tensor = torch.tensor([1, 2, 3, 4])
print("Tensor from list:\n", list_tensor, "\n")

Tensor from list:
 tensor([1, 2, 3, 4]) 



## 2.2 arange

By invoking arange(n), we can create a vector of evenly spaced values, starting at 0 (included) and ending at n (not included).
By default, the interval size is 1. Unless otherwise specified, new tensors are stored in main memory and designated for CPU-based
computation.

In [ ]:
x = torch.arange(12, dtype=torch.float32)
x

In [ ]:
y = x.reshape((3, 4))
y

Each of these values is called an element of the tensor. The tensor x contains 12 elements.

In [ ]:
# Exercise
# Using arrange and reshape, create a tonsor of (3, 6, 4)
# Print 3rd element in the first column of the second matrix.

# 3. Attributes of Tensors

In [ ]:
# Create a random tensor with shape 3x4
tensor = torch.rand(3,4)

In [ ]:
# We can inspect the total number of elements in a tensor via its numel method
print(f"total number of elements: {tensor.numel()}")

In [ ]:
# We can access a tensor’sshape (the length along each axis) by inspecting its shape attribute
print(f"Shape of tensor: {tensor.shape}")

In [ ]:
# Print data type of tensor
print(f"Datatype of tensor: {tensor.dtype}")

In [ ]:
# Exercise - Print the device tensor is stored on


# 4. Operations on tensors

## 4.1 Tensor Indexing and Slicing

Similar to numpy arrays, elements of tensors can be accessed and modified using indexing and slicing. Indexing allows accessing specific elements, rows, or columns, while slicing enables accessing sub-tensors by specifying ranges for each dimension.

We can access tensor elements by indexing (starting with 0). To access an element based on its position relative to the end of the list, we can use negative indexing.

We can access whole ranges of indices via slicing (e.g., X[start:stop]), where the returned value includes the first index (start) but not the last (stop). 

Finally, when only one index (or slice) is specified for a 𝑘 th-order tensor, it is applied along axis 0. Thus, in the following code, [-1] selects the last row and [1:3] selects the second and third rows.

In [ ]:
# Create an example tensor
tensor = torch.tensor([[2, 4, 6, 8], [1, 3, 5, 9], [3, 5, 7, 9]])

# Print the original tensor
print("Original tensor:\n", tensor, "\n")

In [ ]:
# Access and print specific elements
print("Element at row 1, column 2:", tensor[1, 2].item())

In [ ]:
# Access and print the first row of the tensor
print('First row: ', tensor[0])

# Access and print the first column of the tensor
print('First column: ', tensor[:, 0], "\n")

In [ ]:
# Exercise - print the last row and the last column.

In [ ]:
# Slice and print sub-tensors
print("First two rows:\n", tensor[:2, :])
print("Elements from row 1 to end, columns 2 to end:\n", tensor[1:, 2:], "\n")

In [ ]:
# Update a specific element in the tensor
tensor[2, 3] = 23
print("Tensor after updating the element at row 2, column 3 to 23:\n", tensor, "\n")

In [ ]:
# Update an entire column in the tensor
tensor[:, 1] = 10
print("Tensor after updating the entire second column to 10:\n", tensor, "\n")

In [ ]:
# If we want to assign multiple elements the same value, we apply the indexing on the lefthand side of the assignment operation.
# For instance, [:2, :] accesses the first and second rows, where : takes all the elements along axis 1 (column).

# Update multiple elements at once (first two rows)
tensor[:2, :] = 18
print("Tensor after updating the first two rows to 18:\n", tensor)

In [ ]:
# Exercise - Print the second to fourth numbers in the third row in the tensor T.
T = torch.rand(5, 6)
T

## 4.2 Arithmatic operations

PyTorch supports various arithmetic operations such as addition, subtraction, multiplication, and division. These operations can be performed element-wise on tensors of the same shape. Scalar operations (adding, subtracting, multiplying, or dividing a tensor by a scalar) are also supported.

The common standard arithmetic operators for addition (+), subtraction (-), multiplication (*), division (/), and exponentiation (**) have all been lifted to elementwise operations for identically-shaped tensors of arbitrary shape.

In [ ]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

In [ ]:
# Element-wise addition
print("Element-wise addition:\n", tensor_a + tensor_b, "\n")

# Element-wise subtraction
print("Element-wise subtraction:\n", tensor_a - tensor_b, "\n")

# Element-wise multiplication
print("Element-wise multiplication:\n", tensor_a * tensor_b, "\n")

# Element-wise division
print("Element-wise division:\n", tensor_a / tensor_b, "\n")

# Element-wise division
print("Element-wise powering:\n", tensor_a ** tensor_b, "\n")

## 4.3 Tensor Aggregation Operations

Aggregation operations include functions that reduce the tensor to a single value or a smaller tensor. Common operations are `sum()`, `mean()`, `max()`, `min()`, and their variants along specific dimensions (e.g., summing all elements along rows or columns).

In [ ]:
tensor = torch.tensor([[1.0, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# Sum of all elements
print("Sum of all elements:", tensor.sum().item())

# Mean of all elements
print("Mean of all elements:", tensor.mean().item())

# Maximum value
print("Maximum value:", tensor.max().item())

# Minimum value
print("Minimum value:", tensor.min().item())

# Sum along a specific dimension
print("Sum along columns:\n", tensor.sum(dim=0))

# Mean along a specific dimension
print("Mean along rows:\n", tensor.mean(dim=1))

## 4.4 Tensor Reshaping Operations

Reshaping operations change the shape of a tensor without altering its data. Key operations include `view()`, `reshape()`, `transpose()`, and `permute()`. These functions allow converting a tensor to a different shape, transposing dimensions, or flattening the tensor.

In [ ]:
tensor = torch.rand(2, 3, 4)

In [ ]:
# Reshape the tensor to a different shape
reshaped_tensor = tensor.view(3, 8)
print("Reshaped Tensor (3x8):\n", reshaped_tensor, "\n")

In [ ]:
# Transpose the tensor (swap dimensions)
transposed_tensor = tensor.transpose(0, 1)
print("Transposed Tensor (swap first and second dimensions):\n", transposed_tensor, "\n")

In [ ]:
# Flatten the tensor (convert to 1D)
flattened_tensor = tensor.view(-1)
print("Flattened Tensor:\n", flattened_tensor, "\n")

## 4.5 Tensor Broadcasting

Broadcasting allows performing arithmetic operations on tensors of different shapes. PyTorch automatically expands the smaller tensor along the missing dimensions to match the shape of the larger tensor, enabling element-wise operations without explicitly reshaping.

In [ ]:
tensor_a = torch.tensor([[1.0, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([1.0, 2, 3])

# Broadcasting addition
print("Broadcasting addition:\n", tensor_a + tensor_b, "\n")

## 4.6 Tensor Device Management

PyTorch supports operations on both CPU and GPU. Tensors can be moved between devices using `.to('cpu')` or `.to('cuda')` methods. This is essential for leveraging GPU acceleration for faster computations.

In [ ]:
# Create a tensor on CPU
tensor = torch.tensor([1, 2, 3])
print("Tensor on CPU:\n", tensor, "\n")

# Check if CUDA is available and move the tensor to GPU
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Tensor on GPU:\n", tensor, "\n")
else:
    print("CUDA is not available.")

## 4.7 Matrix Multiplication and Dot Product

In addition to elementwise computations, we can also perform linear algebraic operations, such as dot products and matrix multiplications.

In [ ]:
tensor = torch.tensor([[2,4,6,8],[1,3,5,9],[3,5,7,9]])

# Print the original tensor
print("Original tensor:\n", tensor, "\n")

In [ ]:
# Dot Product

# Dot product (element-wise multiplication)
print("Element-wise multiplication (tensor * tensor):\n", tensor * tensor, "\n")

# Element-wise multiplication using the mul method
print("Element-wise multiplication using tensor.mul(tensor):\n", tensor.mul(tensor), "\n")

In [ ]:
# Matrix multiplication (tensor with its transpose)
print("Matrix multiplication (tensor.matmul(tensor.T)):\n", tensor.matmul(tensor.T))

## 4.8 Joining tensors (concatination)

Tensors can be joined (concatenated) along a specified dimension using functions like `torch.cat()` and `torch.stack()`. Concatenation combines tensors along an existing dimension, while stacking adds a new dimension. Tensors can also be split into smaller tensors using `torch.split()` or `torch.chunk()`.

You can use `torch.cat()` to concatenate a sequence of tensors along a given dimension. `torch.stack()` is a related tensor joining option that concatenates a sequence of tensors along a new dimension.

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

X, Y

In [ ]:
t1 = torch.cat((X, Y), dim=0)
print (t1)

In [ ]:
t2 = torch.cat((X, Y), dim=1)
print (t2)

In [ ]:
t1 = torch.arange(24).reshape((2, 3, 4))
t2 = torch.arange(start=10, end=34).reshape((2, 3, 4))
t1, t2

In [ ]:
# Concatenate tensors t1 and t2 along the first dimension (rows).
# This results in a tensor with more rows, stacking t2 below t1.
t3 = torch.cat((t1, t2), dim=0)

# Concatenate tensors t1 and t2 along the second dimension (columns).
# This results in a tensor with more columns, placing t2 to the right of t1.
t4 = torch.cat((t1, t2), dim=1)

# Concatenate tensors t1 and t2 along the third dimension.
# This dimension is typically for depth in 3D tensors, adding depth from t2 to t1.
t5 = torch.cat((t1, t2), dim=2)

In [ ]:
# Print the concatenated tensors with messages
print("Tensor t3 (concatenated along the first dimension):\n", t3)

In [ ]:
print("\nTensor t4 (concatenated along the second dimension):\n", t4)

In [ ]:
print("\nTensor t5 (concatenated along the third dimension):\n", t5)

## 4.9 Logical Operation
Sometimes, we want to construct a binary tensor via logical statements. Take X == Y as an
example. For each position i, j, if X[i, j] and Y[i, j] are equal, then the corresponding
entry in the result takes value 1, otherwise it takes value 0

In [ ]:
X == Y

In [ ]:
# Exercise - Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?

## 4.10 Inplace Operations

In-place operations modify the tensor directly without creating a new tensor. They are denoted by an underscore at the end of the method name (e.g., `add_()`, `mul_()`). In-place operations are memory efficient but can lead to unintended side effects if not used carefully.

In [ ]:
tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

# Print the original tensor
print("Original tensor:\n", tensor, "\n")

# Print the tensor after adding 5 to each element (non-in-place operation)
print("Tensor after adding 5 (non-in-place operation):\n", tensor.add(5), "\n")

# Print the original tensor again to show it remains unchanged
print("The original tensor after non-in-place addition (should be unchanged):\n", tensor, "\n")

# Add 5 to each element of the tensor (in-place operation)
tensor.add_(5)

# Print the tensor after the in-place addition
print("Tensor after adding 5 (in-place operation):\n", tensor)

## 4.11 Tensor Cloning and Detaching

Cloning creates a copy of the tensor with its own data and computation history, allowing modifications without affecting the original tensor. Detaching a tensor from the computation graph using `.detach()` creates a new tensor that shares data but is not tracked for gradients, which is useful in certain parts of the computation.

In [ ]:
tensor = torch.tensor([1, 2, 3], requires_grad=True)

# Clone the tensor
cloned_tensor = tensor.clone()
print("Cloned Tensor:\n", cloned_tensor, "\n")

# Detach the tensor from the computation graph
detached_tensor = tensor.detach()
print("Detached Tensor:\n", detached_tensor, "\n")