<a href="https://colab.research.google.com/github/mdpw/pytorch-deep-learning/blob/main/00_tensor_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
# Sumani
# 20-7-2024

# Modifyied by M.D.P. Wijesuriya
# 18-7-2025

# Tensor Exercises

In [63]:
import torch

# 1. Tensor Creation

In [64]:
# Create a tensor of shape (5, 3) filled with random values.
tensor = torch.rand(5, 3)

print("Tensor of shape (5, 3):")
print(tensor)

Tensor of shape (5, 3):
tensor([[0.3774, 0.6274, 0.9751],
        [0.6379, 0.9331, 0.0598],
        [0.1974, 0.1095, 0.4987],
        [0.8167, 0.8424, 0.5664],
        [0.0755, 0.7559, 0.2226]])


In [65]:
# Create a tensor of shape (2, 4) filled with ones.
tensor = torch.ones(2, 4)

print("Tensor of shape (2, 4) filled with ones:")
print(tensor)

Tensor of shape (2, 4) filled with ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [66]:
# Create a tensor from a list [5, 10, 15, 20].
tensor = torch.tensor([5, 10, 15, 20])

print("Tensor from list:")
print(tensor)

Tensor from list:
tensor([ 5, 10, 15, 20])


In [67]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.
image_tensor = torch.rand(3, 6, 8)

print("Image Tensor shape:", image_tensor.shape)

Image Tensor shape: torch.Size([3, 6, 8])


# 2. Tensor Indexing and Slicing

In [68]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
# Create a 1D tensor with values from 10 to 21 (22 is exclusive)
values = torch.arange(10, 22)

# Reshape it to (3, 4)
tensor = values.reshape(3, 4)

print("Tensor of shape (3, 4) with values from 10 to 21:")
print(tensor)

Tensor of shape (3, 4) with values from 10 to 21:
tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [69]:
image_tensor

tensor([[[0.1468, 0.4418, 0.7201, 0.4644, 0.1974, 0.8120, 0.3585, 0.5030],
         [0.6882, 0.6288, 0.6238, 0.8276, 0.2552, 0.6281, 0.5467, 0.9461],
         [0.0261, 0.8799, 0.3401, 0.7054, 0.8036, 0.0272, 0.4313, 0.5100],
         [0.7962, 0.8004, 0.2682, 0.3713, 0.2923, 0.7503, 0.2495, 0.4502],
         [0.1479, 0.9878, 0.9123, 0.0496, 0.9318, 0.1190, 0.1116, 0.2752],
         [0.2992, 0.3866, 0.5519, 0.0487, 0.1780, 0.0879, 0.8450, 0.4134]],

        [[0.6487, 0.4961, 0.7969, 0.0702, 0.4220, 0.6206, 0.0056, 0.3519],
         [0.9625, 0.2422, 0.9978, 0.3364, 0.2195, 0.2669, 0.0193, 0.4124],
         [0.2002, 0.8847, 0.7258, 0.6132, 0.5966, 0.3645, 0.8214, 0.8529],
         [0.2051, 0.0081, 0.0256, 0.3067, 0.2901, 0.5587, 0.9817, 0.4109],
         [0.3467, 0.9554, 0.9772, 0.2565, 0.3365, 0.9598, 0.8912, 0.0908],
         [0.4578, 0.1829, 0.7618, 0.5014, 0.0326, 0.3404, 0.4250, 0.2244]],

        [[0.6503, 0.2931, 0.5782, 0.1891, 0.1526, 0.6105, 0.5137, 0.4549],
         [0.7894, 0.3

In [70]:
# Access the element at the second row, third column.
element = image_tensor[0, 1, 2]
print("Element at channel 0, row 1, column 2:", element)

Element at channel 0, row 1, column 2: tensor(0.6238)


In [71]:
# Print the second row.
second_row = image_tensor[:, 1, :]  # This means All channels, row 1, all columns
print("Second row (across all channels):")
print(second_row)

Second row (across all channels):
tensor([[0.6882, 0.6288, 0.6238, 0.8276, 0.2552, 0.6281, 0.5467, 0.9461],
        [0.9625, 0.2422, 0.9978, 0.3364, 0.2195, 0.2669, 0.0193, 0.4124],
        [0.7894, 0.3836, 0.2552, 0.7374, 0.2784, 0.2357, 0.6989, 0.6046]])


In [72]:
# Print the first two columns.
first_two_columns = image_tensor[:, :, :2]  # This means All channels, all rows, first 2 columns
print("First two columns (across all rows and channels):")
print(first_two_columns)

First two columns (across all rows and channels):
tensor([[[0.1468, 0.4418],
         [0.6882, 0.6288],
         [0.0261, 0.8799],
         [0.7962, 0.8004],
         [0.1479, 0.9878],
         [0.2992, 0.3866]],

        [[0.6487, 0.4961],
         [0.9625, 0.2422],
         [0.2002, 0.8847],
         [0.2051, 0.0081],
         [0.3467, 0.9554],
         [0.4578, 0.1829]],

        [[0.6503, 0.2931],
         [0.7894, 0.3836],
         [0.7834, 0.1236],
         [0.9078, 0.7191],
         [0.2670, 0.8993],
         [0.6766, 0.9626]]])


# 3. Tensor Arithmetic Operations

In [73]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.
tensor_a = torch.rand(3, 3)
tensor_b = torch.rand(3, 3)

print("tensor a:")
print(tensor_a)

print("\n")

print("tensor b:")
print(tensor_b)

tensor a:
tensor([[0.3073, 0.1653, 0.4811],
        [0.1101, 0.3285, 0.7805],
        [0.8020, 0.2676, 0.2895]])


tensor b:
tensor([[0.3193, 0.6618, 0.4418],
        [0.3361, 0.8868, 0.6629],
        [0.1743, 0.9746, 0.9745]])


In [74]:
# Perform element-wise addition.
result = tensor_a + tensor_b

print("\nElement-wise addition result:")
print(result)


Element-wise addition result:
tensor([[0.6266, 0.8271, 0.9229],
        [0.4462, 1.2153, 1.4434],
        [0.9763, 1.2422, 1.2640]])


In [75]:
# Perform element-wise multiplication.
result = tensor_a * tensor_b

print("\nElement-wise multiplication result:")
print(result)


Element-wise multiplication result:
tensor([[0.0981, 0.1094, 0.2125],
        [0.0370, 0.2913, 0.5174],
        [0.1398, 0.2608, 0.2821]])


In [76]:
# Subtract tensor_b from tensor_a.
result = tensor_a - tensor_b

print("\nResult of tensor_a - tensor_b:")
print(result)


Result of tensor_a - tensor_b:
tensor([[-0.0119, -0.4966,  0.0393],
        [-0.2261, -0.5583,  0.1175],
        [ 0.6277, -0.7070, -0.6850]])


# 4. Tensor Aggregation Operations

In [77]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.
# Create a 1D tensor with values from 1 to 9 (inclusive)
values = torch.arange(1, 10)

# Reshape it to (3, 3)
tensor = values.reshape(3, 3)

print("Tensor of shape (3, 3) with values from 1 to 9:")
print(tensor)

Tensor of shape (3, 3) with values from 1 to 9:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [78]:
# Compute the sum of all elements.
total_sum = tensor.sum()

print("\nSum of all elements:", total_sum.item())


Sum of all elements: 45


In [79]:
# Compute the mean of all elements.
tensor = torch.arange(1, 10).reshape(3, 3).float()  # convert to float for mean

mean_value = tensor.mean()

print("\nMean of all elements:", mean_value.item())


Mean of all elements: 5.0


In [80]:
# Find the maximum and minimum values.
tensor = torch.arange(1, 10).reshape(3, 3)

# Find maximum and minimum values
max_value = tensor.max()
min_value = tensor.min()

print("\nMaximum value:", max_value.item())
print("Minimum value:", min_value.item())


Maximum value: 9
Minimum value: 1


In [81]:
# Compute the sum along the rows.
row_sums = tensor.sum(dim=1)

print("\nSum along the rows:")
print(row_sums)


Sum along the rows:
tensor([ 6, 15, 24])


In [82]:
# Create the tensor with values 1 to 9 and convert to float
tensor = torch.arange(1, 10).reshape(3, 3).float()

# Compute the mean along the columns.
column_means = tensor.mean(dim=0)

print("\nMean along the columns:")
print(column_means)


Mean along the columns:
tensor([4., 5., 6.])


# 5. Tensor Reshaping Operations

In [83]:
# Create a tensor tensor of shape (2, 3, 4) with random values.
tensor = torch.rand(2, 3, 4)

print("Tensor of shape (2, 3, 4) with random values:")
print(tensor)

Tensor of shape (2, 3, 4) with random values:
tensor([[[0.5725, 0.5271, 0.8191, 0.6934],
         [0.4049, 0.4073, 0.1077, 0.9587],
         [0.9150, 0.2209, 0.6163, 0.3193]],

        [[0.3568, 0.1828, 0.9062, 0.1948],
         [0.7745, 0.8278, 0.1922, 0.5391],
         [0.7121, 0.3895, 0.5115, 0.9452]]])


In [84]:
# Reshape the tensor to (4, 6).
reshaped_tensor = tensor.reshape(4, 6)

print("Original tensor shape:", tensor.shape)
print("Reshaped tensor shape:", reshaped_tensor.shape)
print("\nReshaped Tensor:")
print(reshaped_tensor)

Original tensor shape: torch.Size([2, 3, 4])
Reshaped tensor shape: torch.Size([4, 6])

Reshaped Tensor:
tensor([[0.5725, 0.5271, 0.8191, 0.6934, 0.4049, 0.4073],
        [0.1077, 0.9587, 0.9150, 0.2209, 0.6163, 0.3193],
        [0.3568, 0.1828, 0.9062, 0.1948, 0.7745, 0.8278],
        [0.1922, 0.5391, 0.7121, 0.3895, 0.5115, 0.9452]])


In [85]:
# Transpose the tensor (swap the first and second dimensions).
transposed_tensor = tensor.transpose(0, 1)

print("Original shape:", tensor.shape)
print("Transposed shape:", transposed_tensor.shape)
print("\nTransposed Tensor:")
print(transposed_tensor)

Original shape: torch.Size([2, 3, 4])
Transposed shape: torch.Size([3, 2, 4])

Transposed Tensor:
tensor([[[0.5725, 0.5271, 0.8191, 0.6934],
         [0.3568, 0.1828, 0.9062, 0.1948]],

        [[0.4049, 0.4073, 0.1077, 0.9587],
         [0.7745, 0.8278, 0.1922, 0.5391]],

        [[0.9150, 0.2209, 0.6163, 0.3193],
         [0.7121, 0.3895, 0.5115, 0.9452]]])


In [86]:
# Flatten the tensor to a 1D tensor.
flattened_tensor = tensor.view(-1)

print("Original shape:", tensor.shape)
print("Flattened shape:", flattened_tensor.shape)
print("\nFlattened Tensor:")
print(flattened_tensor)

Original shape: torch.Size([2, 3, 4])
Flattened shape: torch.Size([24])

Flattened Tensor:
tensor([0.5725, 0.5271, 0.8191, 0.6934, 0.4049, 0.4073, 0.1077, 0.9587, 0.9150,
        0.2209, 0.6163, 0.3193, 0.3568, 0.1828, 0.9062, 0.1948, 0.7745, 0.8278,
        0.1922, 0.5391, 0.7121, 0.3895, 0.5115, 0.9452])


# 6. Tensor Broadcasting

In [87]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.
tensor_a = torch.arange(1, 7).reshape(2, 3)

print("tensor_a:")
print(tensor_a)

tensor_a:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [88]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].
tensor_b = torch.tensor([[1, 2, 3]])

print("tensor_b:")
print(tensor_b)
print("Shape:", tensor_b.shape)

tensor_b:
tensor([[1, 2, 3]])
Shape: torch.Size([1, 3])


In [89]:
# Perform broadcasting addition.
result = tensor_a + tensor_b

print("\nResult of broadcasting addition:")
print(result)


Result of broadcasting addition:
tensor([[2, 4, 6],
        [5, 7, 9]])


In [90]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].
tensor_c = torch.tensor([[1], [2], [3]])

print("tensor_c:")
print(tensor_c)
print("Shape:", tensor_c.shape)

tensor_c:
tensor([[1],
        [2],
        [3]])
Shape: torch.Size([3, 1])


In [91]:
# Perform broadcasting multiplication.
# Shapes are not directly broadcastable because broadcasting compares dimensions from the right side. So transpose tensor_c to (1,3)
tensor_c_T = tensor_c.T

result = tensor_a * tensor_c_T

print("tensor_a:")
print(tensor_a)

print("\ntensor_c.T:")
print(tensor_c_T)

print("\nBroadcasting multiplication result:")
print(result)

tensor_a:
tensor([[1, 2, 3],
        [4, 5, 6]])

tensor_c.T:
tensor([[1, 2, 3]])

Broadcasting multiplication result:
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])


# 7. Tensor Device Management

In [92]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).
tensor = torch.rand(3, 3)

# Check if CUDA (GPU) is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Move tensor to the selected device (GPU or CPU)
tensor = tensor.to(device)

print(tensor)

tensor([[0.4456, 0.4421, 0.8628],
        [0.7061, 0.1925, 0.9936],
        [0.2243, 0.4233, 0.7045]])


In [93]:
# Verify if the tensor is on GPU.
print(f"Tensor device: {tensor.device}")

# Move the tensor back to CPU.
tensor = tensor.to("cpu")

print(tensor)

Tensor device: cpu
tensor([[0.4456, 0.4421, 0.8628],
        [0.7061, 0.1925, 0.9936],
        [0.2243, 0.4233, 0.7045]])


# 8. Tensor Cloning and Detaching

In [94]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.
tensor = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)

In [95]:
# Clone the tensor and print the cloned tensor.
cloned_tensor = tensor.clone()
print(cloned_tensor)

tensor([1., 2., 3.], grad_fn=<CloneBackward0>)


In [96]:
# Detach the tensor from the computation graph and print the detached tensor.
detached_tensor = tensor.detach()
print(detached_tensor)

tensor([1., 2., 3.])


# 9. High Dimensional Tensors

In [97]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.
tensor_4d = torch.randn(2, 3, 4, 5)
print(tensor_4d)

tensor([[[[ 0.1918, -1.9842, -1.7882, -1.4208, -0.2280],
          [-0.3502,  0.3631,  1.8610, -1.5011, -0.0405],
          [ 0.3554, -0.5713, -0.4315, -0.1894, -0.2981],
          [-0.4809,  0.6559,  0.1832, -1.5149, -1.3097]],

         [[-0.2736,  1.5771,  0.6698, -0.4922,  1.3049],
          [-1.7567,  1.1471,  0.1442, -0.5884, -0.4794],
          [ 1.1266,  0.1155,  1.2551,  1.2747,  0.3998],
          [ 0.4657, -1.1628,  0.5956, -0.1514,  0.6051]],

         [[ 0.7515, -0.0093,  0.8733,  1.2484,  0.4065],
          [ 0.7122, -1.3921,  2.4039, -1.2796, -1.0356],
          [ 0.2924,  1.1565,  0.0263,  0.0447,  0.0349],
          [-0.3709,  0.1404, -0.6481, -0.5157,  1.1553]]],


        [[[ 0.2705, -0.1764, -1.2838, -0.3402,  0.0235],
          [-0.0259, -0.5550, -0.1858, -1.4379, -0.5541],
          [-0.2312, -0.8074,  0.7491, -0.7662,  1.2157],
          [ 1.9721,  0.2106, -1.0850,  2.4261,  0.1833]],

         [[-0.6061, -1.4764, -1.5359, -0.1614, -0.0980],
          [ 0.0913,  

In [98]:
# Print the shape of the tensor.
print(tensor_4d.shape)

torch.Size([2, 3, 4, 5])


In [99]:
# Access the element at position (1, 2, 3, 4).
element = tensor_4d[1, 2, 3, 4]
print(element)

tensor(0.5433)


In [100]:
# Slice and print the first two elements along the first dimension.
sliced_tensor = tensor_4d[:2]
print(sliced_tensor)

tensor([[[[ 0.1918, -1.9842, -1.7882, -1.4208, -0.2280],
          [-0.3502,  0.3631,  1.8610, -1.5011, -0.0405],
          [ 0.3554, -0.5713, -0.4315, -0.1894, -0.2981],
          [-0.4809,  0.6559,  0.1832, -1.5149, -1.3097]],

         [[-0.2736,  1.5771,  0.6698, -0.4922,  1.3049],
          [-1.7567,  1.1471,  0.1442, -0.5884, -0.4794],
          [ 1.1266,  0.1155,  1.2551,  1.2747,  0.3998],
          [ 0.4657, -1.1628,  0.5956, -0.1514,  0.6051]],

         [[ 0.7515, -0.0093,  0.8733,  1.2484,  0.4065],
          [ 0.7122, -1.3921,  2.4039, -1.2796, -1.0356],
          [ 0.2924,  1.1565,  0.0263,  0.0447,  0.0349],
          [-0.3709,  0.1404, -0.6481, -0.5157,  1.1553]]],


        [[[ 0.2705, -0.1764, -1.2838, -0.3402,  0.0235],
          [-0.0259, -0.5550, -0.1858, -1.4379, -0.5541],
          [-0.2312, -0.8074,  0.7491, -0.7662,  1.2157],
          [ 1.9721,  0.2106, -1.0850,  2.4261,  0.1833]],

         [[-0.6061, -1.4764, -1.5359, -0.1614, -0.0980],
          [ 0.0913,  

In [101]:
# Sum all elements in the tensor.
total_sum = tensor_4d.sum()
print(total_sum)

tensor(2.3338)


In [102]:
# Compute the mean along the third dimension.
mean_along_dim3 = tensor_4d.mean(dim=2)
print(mean_along_dim3)
print(mean_along_dim3.shape)

tensor([[[-0.0710, -0.3841, -0.0439, -1.1565, -0.4691],
         [-0.1095,  0.4192,  0.6662,  0.0107,  0.4576],
         [ 0.3463, -0.0261,  0.6639, -0.1256,  0.1403]],

        [[ 0.4964, -0.3320, -0.4514, -0.0295,  0.2171],
         [ 0.0173, -0.6364,  0.2347, -0.6026,  0.8350],
         [ 0.5350, -0.3798,  0.6729, -0.4350,  0.1235]]])
torch.Size([2, 3, 5])


# 10. Combining Tensor Operations

In [103]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.
tensor_a = torch.randn(2, 3, 4)
tensor_b = torch.randn(2, 3, 4)

print("tensor_a:\n", tensor_a)
print("tensor_b:\n", tensor_b)

tensor_a:
 tensor([[[-0.0881,  0.4173,  0.9924, -0.3533],
         [-0.7220,  1.4359,  0.7330, -1.4638],
         [-0.9128, -0.5306, -0.2671, -0.5888]],

        [[-0.9412, -1.3429,  0.5338, -0.7185],
         [ 1.1425,  0.3387,  0.0434,  0.9065],
         [ 0.5658,  0.7867, -0.9897,  0.5975]]])
tensor_b:
 tensor([[[ 0.9352, -0.4696,  0.4798, -0.3758],
         [-0.2747, -1.4931,  0.4770, -1.6100],
         [-0.1088, -0.7706,  1.1854, -0.8124]],

        [[-2.0210,  0.6424,  0.1450,  0.5464],
         [ 0.5093, -0.4154,  1.7517, -0.5867],
         [-0.1501,  2.1410, -1.3081,  1.4038]]])


In [104]:
# Add the two tensors.
tensor_sum = torch.add(tensor_a, tensor_b)
print(tensor_sum)

tensor([[[ 0.8472, -0.0523,  1.4723, -0.7292],
         [-0.9966, -0.0571,  1.2099, -3.0737],
         [-1.0216, -1.3012,  0.9183, -1.4012]],

        [[-2.9622, -0.7005,  0.6788, -0.1721],
         [ 1.6518, -0.0767,  1.7951,  0.3198],
         [ 0.4157,  2.9277, -2.2978,  2.0012]]])


In [105]:
# Multiply the resulting tensor by 2.
tensor_scaled = torch.mul(tensor_sum, 2)
print(tensor_scaled)

tensor([[[ 1.6943, -0.1045,  2.9445, -1.4583],
         [-1.9932, -0.1143,  2.4198, -6.1475],
         [-2.0432, -2.6024,  1.8366, -2.8023]],

        [[-5.9244, -1.4010,  1.3575, -0.3443],
         [ 3.3036, -0.1533,  3.5903,  0.6397],
         [ 0.8313,  5.8555, -4.5956,  4.0025]]])


In [106]:
# Reshape the tensor to (4, 6).
tensor_reshaped = tensor_scaled.reshape(4, 6)
print(tensor_reshaped)

tensor([[ 1.6943, -0.1045,  2.9445, -1.4583, -1.9932, -0.1143],
        [ 2.4198, -6.1475, -2.0432, -2.6024,  1.8366, -2.8023],
        [-5.9244, -1.4010,  1.3575, -0.3443,  3.3036, -0.1533],
        [ 3.5903,  0.6397,  0.8313,  5.8555, -4.5956,  4.0025]])


In [107]:
# Compute the sum along the columns.
column_sums = tensor_reshaped.sum(dim=0)
print(column_sums)

tensor([ 1.7801, -7.0133,  3.0902,  1.4505, -1.4487,  0.9326])


-------------------------------------------- END ----------------------------------------------