In [59]:
# M.D.P. Wijesuriya
# 18-7-2025

# Tensor Exercises

In [60]:
import torch

# 1. Tensor Creation

In [61]:
# Create a tensor of shape (5, 3) filled with random values.
tensor = torch.rand(5, 3)

print("Tensor of shape (5, 3):")
print(tensor)

Tensor of shape (5, 3):
tensor([[0.8185, 0.8244, 0.8343],
        [0.3945, 0.0754, 0.8262],
        [0.1442, 0.5283, 0.9736],
        [0.4041, 0.7117, 0.4093],
        [0.3541, 0.6682, 0.7174]])


In [62]:
# Create a tensor of shape (2, 4) filled with ones.
tensor = torch.ones(2, 4)

print("Tensor of shape (2, 4) filled with ones:")
print(tensor)

Tensor of shape (2, 4) filled with ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [63]:
# Create a tensor from a list [5, 10, 15, 20].
tensor = torch.tensor([5, 10, 15, 20])

print("Tensor from list:")
print(tensor)

Tensor from list:
tensor([ 5, 10, 15, 20])


In [64]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.
image_tensor = torch.rand(3, 6, 8)

print("Image Tensor shape:", image_tensor.shape)

Image Tensor shape: torch.Size([3, 6, 8])


# 2. Tensor Indexing and Slicing

In [65]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
# Create a 1D tensor with values from 10 to 21 (22 is exclusive)
values = torch.arange(10, 22)

# Reshape it to (3, 4)
tensor = values.reshape(3, 4)

print("Tensor of shape (3, 4) with values from 10 to 21:")
print(tensor)

Tensor of shape (3, 4) with values from 10 to 21:
tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [66]:
image_tensor

tensor([[[0.8540, 0.4583, 0.8914, 0.8537, 0.9749, 0.0371, 0.0983, 0.8042],
         [0.7580, 0.8009, 0.5328, 0.8669, 0.1463, 0.1797, 0.5799, 0.1579],
         [0.4253, 0.4415, 0.9124, 0.6002, 0.6727, 0.9569, 0.2611, 0.3761],
         [0.7812, 0.9407, 0.9481, 0.0486, 0.9730, 0.8318, 0.4892, 0.1318],
         [0.7405, 0.9830, 0.9620, 0.4658, 0.8703, 0.7079, 0.0933, 0.4883],
         [0.8512, 0.9823, 0.0101, 0.2456, 0.0249, 0.0909, 0.3603, 0.9059]],

        [[0.5084, 0.0245, 0.7289, 0.1685, 0.6683, 0.9143, 0.5260, 0.3007],
         [0.2907, 0.4004, 0.6515, 0.8130, 0.9334, 0.3332, 0.0809, 0.0831],
         [0.0079, 0.3883, 0.7125, 0.2979, 0.2825, 0.1986, 0.7510, 0.9794],
         [0.5562, 0.0081, 0.5561, 0.3748, 0.3152, 0.3297, 0.5013, 0.4437],
         [0.5631, 0.7435, 0.9986, 0.2227, 0.6815, 0.9768, 0.5786, 0.6218],
         [0.4392, 0.4422, 0.9142, 0.2164, 0.3292, 0.9566, 0.4595, 0.2996]],

        [[0.6895, 0.0666, 0.1908, 0.4100, 0.8559, 0.8182, 0.1299, 0.0126],
         [0.9600, 0.8

In [67]:
# Access the element at the second row, third column.
element = image_tensor[0, 1, 2]
print("Element at channel 0, row 1, column 2:", element)

Element at channel 0, row 1, column 2: tensor(0.5328)


In [68]:
# Print the second row.
second_row = image_tensor[:, 1, :]  # This means All channels, row 1, all columns
print("Second row (across all channels):")
print(second_row)

Second row (across all channels):
tensor([[0.7580, 0.8009, 0.5328, 0.8669, 0.1463, 0.1797, 0.5799, 0.1579],
        [0.2907, 0.4004, 0.6515, 0.8130, 0.9334, 0.3332, 0.0809, 0.0831],
        [0.9600, 0.8666, 0.5534, 0.0985, 0.9791, 0.4234, 0.2237, 0.7807]])


In [69]:
# Print the first two columns.
first_two_columns = image_tensor[:, :, :2]  # This means All channels, all rows, first 2 columns
print("First two columns (across all rows and channels):")
print(first_two_columns)

First two columns (across all rows and channels):
tensor([[[0.8540, 0.4583],
         [0.7580, 0.8009],
         [0.4253, 0.4415],
         [0.7812, 0.9407],
         [0.7405, 0.9830],
         [0.8512, 0.9823]],

        [[0.5084, 0.0245],
         [0.2907, 0.4004],
         [0.0079, 0.3883],
         [0.5562, 0.0081],
         [0.5631, 0.7435],
         [0.4392, 0.4422]],

        [[0.6895, 0.0666],
         [0.9600, 0.8666],
         [0.4893, 0.5321],
         [0.7847, 0.4396],
         [0.6073, 0.5982],
         [0.6213, 0.2025]]])


# 3. Tensor Arithmetic Operations

In [70]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.
tensor_a = torch.rand(3, 3)
tensor_b = torch.rand(3, 3)

print("Tensor A:")
print(tensor_a)

print("\n")

print("\nTensor B:")
print(tensor_b)

Tensor A:
tensor([[0.5749, 0.1991, 0.2199],
        [0.8112, 0.2742, 0.3828],
        [0.7344, 0.7038, 0.1992]])



Tensor B:
tensor([[0.6180, 0.6689, 0.8575],
        [0.8253, 0.9764, 0.6162],
        [0.1122, 0.7545, 0.9140]])


In [106]:
# Perform element-wise addition.
result = tensor_a + tensor_b

print("\nElement-wise addition result:")
print(result)


Element-wise addition result:
tensor([[1.1929, 0.8680, 1.0773],
        [1.6365, 1.2506, 0.9990],
        [0.8466, 1.4583, 1.1133]])


In [72]:
# Perform element-wise multiplication.

In [73]:
# Subtract tensor_b from tensor_a.

# 4. Tensor Aggregation Operations

In [74]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.

In [75]:
# Compute the sum of all elements.

In [76]:
# Compute the mean of all elements.

In [77]:
# Find the maximum and minimum values.

In [78]:
# Compute the sum along the rows.

In [79]:
# Compute the mean along the columns.

# 5. Tensor Reshaping Operations

In [80]:
# Create a tensor tensor of shape (2, 3, 4) with random values.

In [81]:
# Reshape the tensor to (4, 6).

In [82]:
# Transpose the tensor (swap the first and second dimensions).

In [83]:
# Flatten the tensor to a 1D tensor.

# 6. Tensor Broadcasting

In [84]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.

In [85]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].

In [86]:
# Perform broadcasting addition.

In [87]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].

In [88]:
# Perform broadcasting multiplication.

# 7. Tensor Device Management

In [89]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).

In [90]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

# 8. Tensor Cloning and Detaching

In [91]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.

In [92]:
# Clone the tensor and print the cloned tensor.

In [93]:
# Detach the tensor from the computation graph and print the detached tensor.

# 9. High Dimensional Tensors

In [94]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.

In [95]:
# Print the shape of the tensor.

In [96]:
# Access the element at position (1, 2, 3, 4).

In [97]:
# Slice and print the first two elements along the first dimension.

In [98]:
# Sum all elements in the tensor.

In [99]:
# Compute the mean along the third dimension.

# 10. Combining Tensor Operations

In [100]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.

In [101]:
# Add the two tensors.

In [102]:
# Multiply the resulting tensor by 2.

In [103]:
# Reshape the tensor to (4, 6).

In [104]:
# Compute the sum along the columns.

-------------------------------------------- END ----------------------------------------------