In [196]:
# M.D.P. Wijesuriya
# 18-7-2025

# Tensor Exercises

In [197]:
import torch

# 1. Tensor Creation

In [198]:
# Create a tensor of shape (5, 3) filled with random values.
tensor = torch.rand(5, 3)

print("Tensor of shape (5, 3):")
print(tensor)

Tensor of shape (5, 3):
tensor([[0.0199, 0.1905, 0.4290],
        [0.1363, 0.1966, 0.0316],
        [0.5440, 0.8224, 0.1677],
        [0.2714, 0.2008, 0.1246],
        [0.3153, 0.8828, 0.2674]])


In [199]:
# Create a tensor of shape (2, 4) filled with ones.
tensor = torch.ones(2, 4)

print("Tensor of shape (2, 4) filled with ones:")
print(tensor)

Tensor of shape (2, 4) filled with ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [200]:
# Create a tensor from a list [5, 10, 15, 20].
tensor = torch.tensor([5, 10, 15, 20])

print("Tensor from list:")
print(tensor)

Tensor from list:
tensor([ 5, 10, 15, 20])


In [201]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.
image_tensor = torch.rand(3, 6, 8)

print("Image Tensor shape:", image_tensor.shape)

Image Tensor shape: torch.Size([3, 6, 8])


# 2. Tensor Indexing and Slicing

In [202]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
# Create a 1D tensor with values from 10 to 21 (22 is exclusive)
values = torch.arange(10, 22)

# Reshape it to (3, 4)
tensor = values.reshape(3, 4)

print("Tensor of shape (3, 4) with values from 10 to 21:")
print(tensor)

Tensor of shape (3, 4) with values from 10 to 21:
tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [203]:
image_tensor

tensor([[[0.6727, 0.4833, 0.1261, 0.0220, 0.3752, 0.0350, 0.7330, 0.2443],
         [0.9953, 0.5338, 0.4530, 0.9338, 0.3525, 0.9065, 0.9352, 0.1444],
         [0.0500, 0.3006, 0.5561, 0.1893, 0.0834, 0.5672, 0.1019, 0.6317],
         [0.8274, 0.9440, 0.3132, 0.6539, 0.6402, 0.4854, 0.8166, 0.2308],
         [0.8531, 0.6311, 0.4907, 0.6620, 0.3996, 0.4125, 0.8126, 0.6984],
         [0.2880, 0.5121, 0.8207, 0.7867, 0.5676, 0.2210, 0.1005, 0.5955]],

        [[0.6503, 0.0977, 0.9228, 0.3337, 0.1285, 0.4163, 0.4589, 0.9107],
         [0.4476, 0.9933, 0.0644, 0.4773, 0.2834, 0.0690, 0.1815, 0.1670],
         [0.3230, 0.7949, 0.1039, 0.5970, 0.6844, 0.9394, 0.1649, 0.0055],
         [0.5630, 0.3848, 0.4955, 0.5564, 0.4883, 0.4652, 0.6640, 0.5642],
         [0.1999, 0.8225, 0.2380, 0.8234, 0.7245, 0.4828, 0.5745, 0.8080],
         [0.2075, 0.4969, 0.4595, 0.9199, 0.3057, 0.6591, 0.8169, 0.5958]],

        [[0.7585, 0.4975, 0.2960, 0.5404, 0.5245, 0.9492, 0.0637, 0.5241],
         [0.2031, 0.0

In [204]:
# Access the element at the second row, third column.
element = image_tensor[0, 1, 2]
print("Element at channel 0, row 1, column 2:", element)

Element at channel 0, row 1, column 2: tensor(0.4530)


In [205]:
# Print the second row.
second_row = image_tensor[:, 1, :]  # This means All channels, row 1, all columns
print("Second row (across all channels):")
print(second_row)

Second row (across all channels):
tensor([[0.9953, 0.5338, 0.4530, 0.9338, 0.3525, 0.9065, 0.9352, 0.1444],
        [0.4476, 0.9933, 0.0644, 0.4773, 0.2834, 0.0690, 0.1815, 0.1670],
        [0.2031, 0.0741, 0.8500, 0.1314, 0.5944, 0.9870, 0.6500, 0.7861]])


In [206]:
# Print the first two columns.
first_two_columns = image_tensor[:, :, :2]  # This means All channels, all rows, first 2 columns
print("First two columns (across all rows and channels):")
print(first_two_columns)

First two columns (across all rows and channels):
tensor([[[0.6727, 0.4833],
         [0.9953, 0.5338],
         [0.0500, 0.3006],
         [0.8274, 0.9440],
         [0.8531, 0.6311],
         [0.2880, 0.5121]],

        [[0.6503, 0.0977],
         [0.4476, 0.9933],
         [0.3230, 0.7949],
         [0.5630, 0.3848],
         [0.1999, 0.8225],
         [0.2075, 0.4969]],

        [[0.7585, 0.4975],
         [0.2031, 0.0741],
         [0.9948, 0.2282],
         [0.1144, 0.2673],
         [0.3586, 0.7015],
         [0.7465, 0.4558]]])


# 3. Tensor Arithmetic Operations

In [207]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.
tensor_a = torch.rand(3, 3)
tensor_b = torch.rand(3, 3)

print("tensor a:")
print(tensor_a)

print("\n")

print("tensor b:")
print(tensor_b)

tensor a:
tensor([[0.6096, 0.3445, 0.2852],
        [0.3863, 0.2040, 0.0291],
        [0.2330, 0.7021, 0.4459]])


tensor b:
tensor([[0.2581, 0.4061, 0.5449],
        [0.8514, 0.9207, 0.4458],
        [0.6586, 0.2245, 0.7075]])


In [208]:
# Perform element-wise addition.
result = tensor_a + tensor_b

print("\nElement-wise addition result:")
print(result)


Element-wise addition result:
tensor([[0.8677, 0.7506, 0.8301],
        [1.2377, 1.1247, 0.4749],
        [0.8916, 0.9266, 1.1535]])


In [209]:
# Perform element-wise multiplication.
result = tensor_a * tensor_b

print("\nElement-wise multiplication result:")
print(result)


Element-wise multiplication result:
tensor([[0.1574, 0.1399, 0.1554],
        [0.3289, 0.1879, 0.0130],
        [0.1534, 0.1576, 0.3155]])


In [210]:
# Subtract tensor_b from tensor_a.
result = tensor_a - tensor_b

print("\nResult of tensor_a - tensor_b:")
print(result)


Result of tensor_a - tensor_b:
tensor([[ 0.3515, -0.0616, -0.2596],
        [-0.4651, -0.7167, -0.4167],
        [-0.4256,  0.4775, -0.2616]])


# 4. Tensor Aggregation Operations

In [211]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.
# Create a 1D tensor with values from 1 to 9 (inclusive)
values = torch.arange(1, 10)

# Reshape it to (3, 3)
tensor = values.reshape(3, 3)

print("Tensor of shape (3, 3) with values from 1 to 9:")
print(tensor)

Tensor of shape (3, 3) with values from 1 to 9:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [212]:
# Compute the sum of all elements.
total_sum = tensor.sum()

print("\nSum of all elements:", total_sum.item())


Sum of all elements: 45


In [242]:
# Compute the mean of all elements.
tensor = torch.arange(1, 10).reshape(3, 3).float()  # convert to float for mean

mean_value = tensor.mean()

print("\nMean of all elements:", mean_value.item())


Mean of all elements: 5.0


In [243]:
# Find the maximum and minimum values.
tensor = torch.arange(1, 10).reshape(3, 3)

# Find maximum and minimum values
max_value = tensor.max()
min_value = tensor.min()

print("\nMaximum value:", max_value.item())
print("Minimum value:", min_value.item())


Maximum value: 9
Minimum value: 1


In [244]:
# Compute the sum along the rows.
row_sums = tensor.sum(dim=1)

print("\nSum along the rows:")
print(row_sums)


Sum along the rows:
tensor([ 6, 15, 24])


In [247]:
# Create the tensor with values 1 to 9 and convert to float
tensor = torch.arange(1, 10).reshape(3, 3).float()

# Compute the mean along the columns.
column_means = tensor.mean(dim=0)

print("\nMean along the columns:")
print(column_means)


Mean along the columns:
tensor([4., 5., 6.])


# 5. Tensor Reshaping Operations

In [248]:
# Create a tensor tensor of shape (2, 3, 4) with random values.
tensor = torch.rand(2, 3, 4)

print("Tensor of shape (2, 3, 4) with random values:")
print(tensor)

Tensor of shape (2, 3, 4) with random values:
tensor([[[0.2551, 0.5219, 0.5675, 0.7354],
         [0.1101, 0.5475, 0.4668, 0.7883],
         [0.7017, 0.7592, 0.8416, 0.2262]],

        [[0.6901, 0.6339, 0.4234, 0.1055],
         [0.9536, 0.6047, 0.6131, 0.1127],
         [0.8415, 0.0488, 0.5388, 0.5572]]])


In [249]:
# Reshape the tensor to (4, 6).
reshaped_tensor = tensor.reshape(4, 6)

print("Original tensor shape:", tensor.shape)
print("Reshaped tensor shape:", reshaped_tensor.shape)
print("\nReshaped Tensor:")
print(reshaped_tensor)

Original tensor shape: torch.Size([2, 3, 4])
Reshaped tensor shape: torch.Size([4, 6])

Reshaped Tensor:
tensor([[0.2551, 0.5219, 0.5675, 0.7354, 0.1101, 0.5475],
        [0.4668, 0.7883, 0.7017, 0.7592, 0.8416, 0.2262],
        [0.6901, 0.6339, 0.4234, 0.1055, 0.9536, 0.6047],
        [0.6131, 0.1127, 0.8415, 0.0488, 0.5388, 0.5572]])


In [250]:
# Transpose the tensor (swap the first and second dimensions).
transposed_tensor = tensor.transpose(0, 1)

print("Original shape:", tensor.shape)
print("Transposed shape:", transposed_tensor.shape)
print("\nTransposed Tensor:")
print(transposed_tensor)

Original shape: torch.Size([2, 3, 4])
Transposed shape: torch.Size([3, 2, 4])

Transposed Tensor:
tensor([[[0.2551, 0.5219, 0.5675, 0.7354],
         [0.6901, 0.6339, 0.4234, 0.1055]],

        [[0.1101, 0.5475, 0.4668, 0.7883],
         [0.9536, 0.6047, 0.6131, 0.1127]],

        [[0.7017, 0.7592, 0.8416, 0.2262],
         [0.8415, 0.0488, 0.5388, 0.5572]]])


In [251]:
# Flatten the tensor to a 1D tensor.
flattened_tensor = tensor.view(-1)

print("Original shape:", tensor.shape)
print("Flattened shape:", flattened_tensor.shape)
print("\nFlattened Tensor:")
print(flattened_tensor)

Original shape: torch.Size([2, 3, 4])
Flattened shape: torch.Size([24])

Flattened Tensor:
tensor([0.2551, 0.5219, 0.5675, 0.7354, 0.1101, 0.5475, 0.4668, 0.7883, 0.7017,
        0.7592, 0.8416, 0.2262, 0.6901, 0.6339, 0.4234, 0.1055, 0.9536, 0.6047,
        0.6131, 0.1127, 0.8415, 0.0488, 0.5388, 0.5572])


# 6. Tensor Broadcasting

In [252]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.
tensor_a = torch.arange(1, 7).reshape(2, 3)

print("tensor_a:")
print(tensor_a)

tensor_a:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [253]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].
tensor_b = torch.tensor([[1, 2, 3]])

print("tensor_b:")
print(tensor_b)
print("Shape:", tensor_b.shape)

tensor_b:
tensor([[1, 2, 3]])
Shape: torch.Size([1, 3])


In [255]:
# Perform broadcasting addition.
result = tensor_a + tensor_b

print("\nResult of broadcasting addition:")
print(result)


Result of broadcasting addition:
tensor([[2, 4, 6],
        [5, 7, 9]])


In [256]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].
tensor_c = torch.tensor([[1], [2], [3]])

print("tensor_c:")
print(tensor_c)
print("Shape:", tensor_c.shape)

tensor_c:
tensor([[1],
        [2],
        [3]])
Shape: torch.Size([3, 1])


In [259]:
# Perform broadcasting multiplication.
# Shapes are not directly broadcastable because broadcasting compares dimensions from the right side. So transpose tensor_c to (1,3)
tensor_c_T = tensor_c.T

result = tensor_a * tensor_c_T

print("tensor_a:")
print(tensor_a)

print("\ntensor_c.T:")
print(tensor_c_T)

print("\nBroadcasting multiplication result:")
print(result)

tensor_a:
tensor([[1, 2, 3],
        [4, 5, 6]])

tensor_c.T:
tensor([[1, 2, 3]])

Broadcasting multiplication result:
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])


# 7. Tensor Device Management

In [226]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).

In [227]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

# 8. Tensor Cloning and Detaching

In [228]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.

In [229]:
# Clone the tensor and print the cloned tensor.

In [230]:
# Detach the tensor from the computation graph and print the detached tensor.

# 9. High Dimensional Tensors

In [231]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.

In [232]:
# Print the shape of the tensor.

In [233]:
# Access the element at position (1, 2, 3, 4).

In [234]:
# Slice and print the first two elements along the first dimension.

In [235]:
# Sum all elements in the tensor.

In [236]:
# Compute the mean along the third dimension.

# 10. Combining Tensor Operations

In [237]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.

In [238]:
# Add the two tensors.

In [239]:
# Multiply the resulting tensor by 2.

In [240]:
# Reshape the tensor to (4, 6).

In [241]:
# Compute the sum along the columns.

-------------------------------------------- END ----------------------------------------------